insert into skill (skillID, skillname) values (1, 'Be Your Own Boss');
insert into skill (skillID, skillname) values (2, 'CTR');
insert into skill (skillID, skillname) values (3, 'FF&amp;E');
insert into skill (skillID, skillname) values (4, 'PFMEA');
insert into skill (skillID, skillname) values (5, 'IT Management');
insert into skill (skillID, skillname) values (6, 'HBOC');
insert into skill (skillID, skillname) values (7, 'Branding');
insert into skill (skillID, skillname) values (8, 'Vectorworks');
insert into skill (skillID, skillname) values (9, 'Keyshot');
insert into skill (skillID, skillname) values (10, 'TTS');
insert into skill (skillID, skillname) values (11, 'LTO');
insert into skill (skillID, skillname) values (12, 'HNW');
insert into skill (skillID, skillname) values (13, 'Environmental Policy');
insert into skill (skillID, skillname) values (14, 'MPBGP');
insert into skill (skillID, skillname) values (15, 'AOP');
insert into skill (skillID, skillname) values (16, 'HVAC Controls');
insert into skill (skillID, skillname) values (17, 'BPT');
insert into skill (skillID, skillname) values (18, 'Income Tax');
insert into skill (skillID, skillname) values (19, 'Site Planning');
insert into skill (skillID, skillname) values (20, 'Swaps');
insert into skill (skillID, skillname) values (21, 'Youth Mentoring');
insert into skill (skillID, skillname) values (22, 'Team Mgmt');
insert into skill (skillID, skillname) values (23, 'RTL Coding');
insert into skill (skillID, skillname) values (24, 'Olefins');
insert into skill (skillID, skillname) values (25, 'IBM Certified');
insert into skill (skillID, skillname) values (26, 'DDM');
insert into skill (skillID, skillname) values (27, 'Dynamic Positioning');
insert into skill (skillID, skillname) values (28, 'VTR');
insert into skill (skillID, skillname) values (29, 'Market Analysis');
insert into skill (skillID, skillname) values (30, 'CGI');
insert into skill (skillID, skillname) values (31, 'FDMA');
insert into skill (skillID, skillname) values (32, 'BMPs');
insert into skill (skillID, skillname) values (33, 'PPBES');
insert into skill (skillID, skillname) values (34, 'Invertebrate Zoology');
insert into skill (skillID, skillname) values (35, 'RBAC');
insert into skill (skillID, skillname) values (36, 'Online Gaming');
insert into skill (skillID, skillname) values (37, 'RDCS');
insert into skill (skillID, skillname) values (38, 'NCP');
insert into skill (skillID, skillname) values (39, 'EJB');
insert into skill (skillID, skillname) values (40, 'Vacation');
insert into skill (skillID, skillname) values (41, 'Consulting');
insert into skill (skillID, skillname) values (42, 'TS');
insert into skill (skillID, skillname) values (43, 'Windows 7');
insert into skill (skillID, skillname) values (44, 'Ruby on Rails');
insert into skill (skillID, skillname) values (45, 'Competitive Analysis');
insert into skill (skillID, skillname) values (46, 'Corporate Real Estate');
insert into skill (skillID, skillname) values (47, 'Educational Outreach');
insert into skill (skillID, skillname) values (48, 'CCNP Security');
insert into skill (skillID, skillname) values (49, 'Project Bidding');
insert into skill (skillID, skillname) values (50, 'Epidemiology');
insert into skill (skillID, skillname) values (51, 'Feature Films');
insert into skill (skillID, skillname) values (52, 'ODI');
insert into skill (skillID, skillname) values (53, 'Earned Value Management');
insert into skill (skillID, skillname) values (54, 'EMS');
insert into skill (skillID, skillname) values (55, 'Foreign Affairs');
insert into skill (skillID, skillname) values (56, 'Treatment');
insert into skill (skillID, skillname) values (57, 'Pharmaceutical Industry');
insert into skill (skillID, skillname) values (58, 'Eyewear');
insert into skill (skillID, skillname) values (59, 'FTSE 100');
insert into skill (skillID, skillname) values (60, 'Virtualization');
insert into skill (skillID, skillname) values (61, 'Sports Injuries');
insert into skill (skillID, skillname) values (62, 'CT Summation');
insert into skill (skillID, skillname) values (63, 'Novell');
insert into skill (skillID, skillname) values (64, 'Green Belt');
insert into skill (skillID, skillname) values (65, 'Hardware');
insert into skill (skillID, skillname) values (66, 'TTD');
insert into skill (skillID, skillname) values (67, 'TCP/IP');
insert into skill (skillID, skillname) values (68, 'NX-OS');
insert into skill (skillID, skillname) values (69, 'Data Quality');
insert into skill (skillID, skillname) values (70, 'JDE Enterprise One');
insert into skill (skillID, skillname) values (71, 'User Experience Design');
insert into skill (skillID, skillname) values (72, 'Cashiering');
insert into skill (skillID, skillname) values (73, 'Phone Etiquette');
insert into skill (skillID, skillname) values (74, 'Pre-opening');
insert into skill (skillID, skillname) values (75, 'Spring DM');
insert into skill (skillID, skillname) values (76, 'Environmental Science');
insert into skill (skillID, skillname) values (77, 'OmniPage');
insert into skill (skillID, skillname) values (78, 'Computer Science');
insert into skill (skillID, skillname) values (79, 'WCDMA');
insert into skill (skillID, skillname) values (80, 'NLB');
insert into skill (skillID, skillname) values (81, 'DV');
insert into skill (skillID, skillname) values (82, 'RHEV');
insert into skill (skillID, skillname) values (83, 'ESB');
insert into skill (skillID, skillname) values (84, 'Embedded Software');
insert into skill (skillID, skillname) values (85, 'Electricians');
insert into skill (skillID, skillname) values (86, '1H NMR');
insert into skill (skillID, skillname) values (87, 'CA Unicenter NSM');
insert into skill (skillID, skillname) values (88, 'Numerical Ability');
insert into skill (skillID, skillname) values (89, 'Agile Project Management');
insert into skill (skillID, skillname) values (90, 'Unity3D');
insert into skill (skillID, skillname) values (91, 'NHPA');
insert into skill (skillID, skillname) values (92, 'Windows 7');
insert into skill (skillID, skillname) values (93, 'FFIEC');
insert into skill (skillID, skillname) values (94, 'CGEIT');
insert into skill (skillID, skillname) values (95, 'UHV');
insert into skill (skillID, skillname) values (96, 'NBFC');
insert into skill (skillID, skillname) values (97, 'Sales Cycle Management');
insert into skill (skillID, skillname) values (98, 'Microchip PIC');
insert into skill (skillID, skillname) values (99, 'Navy');
insert into skill (skillID, skillname) values (100, 'EBITDA');
insert into skill (skillID, skillname) values (101, 'Waterfall');
insert into skill (skillID, skillname) values (102, 'jQuery UI');
insert into skill (skillID, skillname) values (103, 'SAP BW');
insert into skill (skillID, skillname) values (104, 'Executive Search');
insert into skill (skillID, skillname) values (105, 'Youth Mentoring');
insert into skill (skillID, skillname) values (106, 'AMI');
insert into skill (skillID, skillname) values (107, 'Service Delivery');
insert into skill (skillID, skillname) values (108, 'HTTPS');
insert into skill (skillID, skillname) values (109, 'GFAS');
insert into skill (skillID, skillname) values (110, 'RLM');
insert into skill (skillID, skillname) values (111, 'Energy');
insert into skill (skillID, skillname) values (112, 'Skin');
insert into skill (skillID, skillname) values (113, 'Rail');
insert into skill (skillID, skillname) values (114, 'IVR');
insert into skill (skillID, skillname) values (115, 'Mining');
insert into skill (skillID, skillname) values (116, 'IAR Embedded Workbench');
insert into skill (skillID, skillname) values (117, 'Switchboard Operator');
insert into skill (skillID, skillname) values (118, 'Parts');
insert into skill (skillID, skillname) values (119, 'Veneers');
insert into skill (skillID, skillname) values (120, 'Drawing');
insert into skill (skillID, skillname) values (121, 'CSA 2010');
insert into skill (skillID, skillname) values (122, 'Baan ERP');
insert into skill (skillID, skillname) values (123, 'Data Entry');
insert into skill (skillID, skillname) values (124, 'JDA');
insert into skill (skillID, skillname) values (125, 'SAP BW');
insert into skill (skillID, skillname) values (126, 'Beer');
insert into skill (skillID, skillname) values (127, 'At-risk');
insert into skill (skillID, skillname) values (128, 'MDSD');
insert into skill (skillID, skillname) values (129, 'Jet Fuel');
insert into skill (skillID, skillname) values (130, 'UDP');
insert into skill (skillID, skillname) values (131, 'Inventory Management');
insert into skill (skillID, skillname) values (132, 'Iyengar Yoga');
insert into skill (skillID, skillname) values (133, 'CCSP');
insert into skill (skillID, skillname) values (134, 'Ektron Content Management System');
insert into skill (skillID, skillname) values (135, 'NLB');
insert into skill (skillID, skillname) values (136, 'Pneumatic Tools');
insert into skill (skillID, skillname) values (137, 'CEO/CFO Certification');
insert into skill (skillID, skillname) values (138, 'ICU');
insert into skill (skillID, skillname) values (139, 'Firewalls');
insert into skill (skillID, skillname) values (140, 'LR');
insert into skill (skillID, skillname) values (141, 'CNC Programming');
insert into skill (skillID, skillname) values (142, 'Private Banking');
insert into skill (skillID, skillname) values (143, 'MCDBA');
insert into skill (skillID, skillname) values (144, 'Knowledge Representation');
insert into skill (skillID, skillname) values (145, 'Design Thinking');
insert into skill (skillID, skillname) values (146, 'PVM');
insert into skill (skillID, skillname) values (147, 'PK');
insert into skill (skillID, skillname) values (148, 'Document Management');
insert into skill (skillID, skillname) values (149, 'Luxury Homes');
insert into skill (skillID, skillname) values (150, 'PL/SQL');
insert into skill (skillID, skillname) values (151, 'RNAi');
insert into skill (skillID, skillname) values (152, 'CPIM');
insert into skill (skillID, skillname) values (153, 'FTK');
insert into skill (skillID, skillname) values (154, 'OSGi');
insert into skill (skillID, skillname) values (155, 'Yield Management');
insert into skill (skillID, skillname) values (156, 'NCIC');
insert into skill (skillID, skillname) values (157, 'Bylaws');
insert into skill (skillID, skillname) values (158, 'Basel II');
insert into skill (skillID, skillname) values (159, 'KWP2000');
insert into skill (skillID, skillname) values (160, 'iPhoto');
insert into skill (skillID, skillname) values (161, 'LLBLGen');
insert into skill (skillID, skillname) values (162, 'Rock Climbing');
insert into skill (skillID, skillname) values (163, 'UCC filings');
insert into skill (skillID, skillname) values (164, 'CCENT');
insert into skill (skillID, skillname) values (165, 'Liability');
insert into skill (skillID, skillname) values (166, 'Kondor+');
insert into skill (skillID, skillname) values (167, 'HP Proliant');
insert into skill (skillID, skillname) values (168, 'FW');
insert into skill (skillID, skillname) values (169, 'Special Education');
insert into skill (skillID, skillname) values (170, 'HDSL');
insert into skill (skillID, skillname) values (171, 'DLS');
insert into skill (skillID, skillname) values (172, 'Object Oriented Modeling');
insert into skill (skillID, skillname) values (173, 'VMware ESX');
insert into skill (skillID, skillname) values (174, 'International Business');
insert into skill (skillID, skillname) values (175, 'Sleep Medicine');
insert into skill (skillID, skillname) values (176, 'Differentiated Instruction');
insert into skill (skillID, skillname) values (177, 'Typewriter');
insert into skill (skillID, skillname) values (178, 'BLS');
insert into skill (skillID, skillname) values (179, 'Runway');
insert into skill (skillID, skillname) values (180, 'UDDI');
insert into skill (skillID, skillname) values (181, 'Petroleum');
insert into skill (skillID, skillname) values (182, 'Jeans');
insert into skill (skillID, skillname) values (183, 'OSGi');
insert into skill (skillID, skillname) values (184, 'CNC Programing');
insert into skill (skillID, skillname) values (185, 'Psychological Testing');
insert into skill (skillID, skillname) values (186, 'Alzheimer&#39;s Disease');
insert into skill (skillID, skillname) values (187, 'PwC TeamMate');
insert into skill (skillID, skillname) values (188, 'uDig');
insert into skill (skillID, skillname) values (189, 'Board Certified');
insert into skill (skillID, skillname) values (190, 'Rent to Own');
insert into skill (skillID, skillname) values (191, 'RRP');
insert into skill (skillID, skillname) values (192, 'Ticket Sales');
insert into skill (skillID, skillname) values (193, 'Eyelid Surgery');
insert into skill (skillID, skillname) values (194, 'Biopharmaceuticals');
insert into skill (skillID, skillname) values (195, 'Video over IP');
insert into skill (skillID, skillname) values (196, 'Information Assurance');
insert into skill (skillID, skillname) values (197, 'Vulnerability Management');
insert into skill (skillID, skillname) values (198, 'Kickboxing');
insert into skill (skillID, skillname) values (199, 'OEE');
insert into skill (skillID, skillname) values (200, 'Soft Skills');
insert into skill (skillID, skillname) values (201, 'Guardianship');
insert into skill (skillID, skillname) values (202, 'Kohana Framework');
insert into skill (skillID, skillname) values (203, 'Oligonucleotide Synthesis');
insert into skill (skillID, skillname) values (204, 'Rural Marketing');
insert into skill (skillID, skillname) values (205, 'CGI');
insert into skill (skillID, skillname) values (206, 'Annual Giving');
insert into skill (skillID, skillname) values (207, 'PTO');
insert into skill (skillID, skillname) values (208, 'Governmental Affairs');
insert into skill (skillID, skillname) values (209, 'jQuery Mobile');
insert into skill (skillID, skillname) values (210, 'ASP.NET');
insert into skill (skillID, skillname) values (211, 'PnL Management');
insert into skill (skillID, skillname) values (212, 'Tds');
insert into skill (skillID, skillname) values (213, 'Occupational Therapy');
insert into skill (skillID, skillname) values (214, 'Hg');
insert into skill (skillID, skillname) values (215, 'Rheology');
insert into skill (skillID, skillname) values (216, 'Kaspersky Antivirus');
insert into skill (skillID, skillname) values (217, 'DSM-IV');
insert into skill (skillID, skillname) values (218, 'MLRO');
insert into skill (skillID, skillname) values (219, 'ERISA');
insert into skill (skillID, skillname) values (220, 'SSADM');
insert into skill (skillID, skillname) values (221, 'Publicity');
insert into skill (skillID, skillname) values (222, 'Storage');
insert into skill (skillID, skillname) values (223, 'VMware Player');
insert into skill (skillID, skillname) values (224, 'Nuke');
insert into skill (skillID, skillname) values (225, 'OJEU');
insert into skill (skillID, skillname) values (226, 'DTMF');
insert into skill (skillID, skillname) values (227, 'Quantitative Research');
insert into skill (skillID, skillname) values (228, 'TKI');
insert into skill (skillID, skillname) values (229, 'Sybase IQ');
insert into skill (skillID, skillname) values (230, 'MySQLi');
insert into skill (skillID, skillname) values (231, 'Simulations');
insert into skill (skillID, skillname) values (232, 'RGB');
insert into skill (skillID, skillname) values (233, 'Shell Scripting');
insert into skill (skillID, skillname) values (234, 'KYC');
insert into skill (skillID, skillname) values (235, 'LSAMS');
insert into skill (skillID, skillname) values (236, 'Vocals');
insert into skill (skillID, skillname) values (237, 'MIS');
insert into skill (skillID, skillname) values (238, 'Axioma');
insert into skill (skillID, skillname) values (239, 'IT Audit');
insert into skill (skillID, skillname) values (240, 'Child Development');
insert into skill (skillID, skillname) values (241, 'Design for Manufacturing');
insert into skill (skillID, skillname) values (242, 'Manual Therapy');
insert into skill (skillID, skillname) values (243, 'Rubber');
insert into skill (skillID, skillname) values (244, 'TFSA');
insert into skill (skillID, skillname) values (245, 'RTK');
insert into skill (skillID, skillname) values (246, 'UltraTax CS');
insert into skill (skillID, skillname) values (247, 'Validation');
insert into skill (skillID, skillname) values (248, 'CMS');
insert into skill (skillID, skillname) values (249, 'Jeep');
insert into skill (skillID, skillname) values (250, 'KOL Identification');
insert into skill (skillID, skillname) values (251, 'Tk');
insert into skill (skillID, skillname) values (252, 'OH&amp;S');
insert into skill (skillID, skillname) values (253, 'Jet Fuel');
insert into skill (skillID, skillname) values (254, 'Adolescents');
insert into skill (skillID, skillname) values (255, 'First Time Home Buyers');
insert into skill (skillID, skillname) values (256, 'Fixed Assets');
insert into skill (skillID, skillname) values (257, 'Signal Processing');
insert into skill (skillID, skillname) values (258, 'WFS');
insert into skill (skillID, skillname) values (259, 'Computer Network Operations');
insert into skill (skillID, skillname) values (260, 'Mineral Exploration');
insert into skill (skillID, skillname) values (261, 'Global Mobility');
insert into skill (skillID, skillname) values (262, 'Orthopedics');
insert into skill (skillID, skillname) values (263, 'Event Management');
insert into skill (skillID, skillname) values (264, 'Public Sector');
insert into skill (skillID, skillname) values (265, 'DSM-IV');
insert into skill (skillID, skillname) values (266, 'ASP');
insert into skill (skillID, skillname) values (267, 'Western Europe');
insert into skill (skillID, skillname) values (268, 'Ektron');
insert into skill (skillID, skillname) values (269, 'TMJ Dysfunction');
insert into skill (skillID, skillname) values (270, 'Pressure Vessels');
insert into skill (skillID, skillname) values (271, 'PVD');
insert into skill (skillID, skillname) values (272, 'Improvisation');
insert into skill (skillID, skillname) values (273, 'DDTS');
insert into skill (skillID, skillname) values (274, 'CFRA');
insert into skill (skillID, skillname) values (275, 'SAP MDM');
insert into skill (skillID, skillname) values (276, 'OS/390');
insert into skill (skillID, skillname) values (277, 'Odeon');
insert into skill (skillID, skillname) values (278, 'Arbitration');
insert into skill (skillID, skillname) values (279, 'Professional Ethics');
insert into skill (skillID, skillname) values (280, 'Assessment Center');
insert into skill (skillID, skillname) values (281, 'IUI');
insert into skill (skillID, skillname) values (282, 'SSP');
insert into skill (skillID, skillname) values (283, 'Zero Waste');
insert into skill (skillID, skillname) values (284, 'HTC');
insert into skill (skillID, skillname) values (285, 'SBEM');
insert into skill (skillID, skillname) values (286, 'Kaizen Leadership');
insert into skill (skillID, skillname) values (287, 'Ext JS');
insert into skill (skillID, skillname) values (288, 'Fashion Jewelry');
insert into skill (skillID, skillname) values (289, 'UV disinfection');
insert into skill (skillID, skillname) values (290, 'Security Clearance');
insert into skill (skillID, skillname) values (291, 'Volunteering');
insert into skill (skillID, skillname) values (292, 'Bookkeeping');
insert into skill (skillID, skillname) values (293, 'SNL');
insert into skill (skillID, skillname) values (294, 'Working at Height');
insert into skill (skillID, skillname) values (295, 'SFX');
insert into skill (skillID, skillname) values (296, 'Databases');
insert into skill (skillID, skillname) values (297, 'Ambulatory');
insert into skill (skillID, skillname) values (298, 'DBI');
insert into skill (skillID, skillname) values (299, 'Vtiger');
insert into skill (skillID, skillname) values (300, 'MGCP');
insert into skill (skillID, skillname) values (301, 'KOL Management');
insert into skill (skillID, skillname) values (302, 'Fertility');
insert into skill (skillID, skillname) values (303, 'Luxury Goods');
insert into skill (skillID, skillname) values (304, 'SI');
insert into skill (skillID, skillname) values (305, 'IACUC');
insert into skill (skillID, skillname) values (306, 'European Studies');
insert into skill (skillID, skillname) values (307, 'OOP');
insert into skill (skillID, skillname) values (308, 'eBay');
insert into skill (skillID, skillname) values (309, 'TIG Welding');
insert into skill (skillID, skillname) values (310, 'User-centered Design');
insert into skill (skillID, skillname) values (311, 'Surgery');
insert into skill (skillID, skillname) values (312, 'Vendor Management');
insert into skill (skillID, skillname) values (313, 'Oil Paint');
insert into skill (skillID, skillname) values (314, 'McData');
insert into skill (skillID, skillname) values (315, 'Materials Science');
insert into skill (skillID, skillname) values (316, 'DBMS');
insert into skill (skillID, skillname) values (317, 'Conservation Issues');
insert into skill (skillID, skillname) values (318, 'TTCN-3');
insert into skill (skillID, skillname) values (319, 'IFTA');
insert into skill (skillID, skillname) values (320, 'Izotope RX');
insert into skill (skillID, skillname) values (321, 'Eyeliner');
insert into skill (skillID, skillname) values (322, 'Leadership Development');
insert into skill (skillID, skillname) values (323, 'Mobile Marketing');
insert into skill (skillID, skillname) values (324, 'Personal Training');
insert into skill (skillID, skillname) values (325, 'Talent Management');
insert into skill (skillID, skillname) values (326, 'Logistics Management');
insert into skill (skillID, skillname) values (327, 'Socket.io');
insert into skill (skillID, skillname) values (328, 'Community Outreach');
insert into skill (skillID, skillname) values (329, 'USB');
insert into skill (skillID, skillname) values (330, 'Feature Articles');
insert into skill (skillID, skillname) values (331, 'Galleries');
insert into skill (skillID, skillname) values (332, 'JavaBeans');
insert into skill (skillID, skillname) values (333, 'Oracle HR');
insert into skill (skillID, skillname) values (334, 'NMLS');
insert into skill (skillID, skillname) values (335, 'GCC');
insert into skill (skillID, skillname) values (336, 'Physician Relations');
insert into skill (skillID, skillname) values (337, 'Merchandising');
insert into skill (skillID, skillname) values (338, 'Annual Giving');
insert into skill (skillID, skillname) values (339, 'ABAP-OO');
insert into skill (skillID, skillname) values (340, 'OmniPage');
insert into skill (skillID, skillname) values (341, 'Xytech');
insert into skill (skillID, skillname) values (342, 'Guerrilla Marketing');
insert into skill (skillID, skillname) values (343, 'Food Preparation');
insert into skill (skillID, skillname) values (344, 'Carriage of Goods by Sea');
insert into skill (skillID, skillname) values (345, 'Pre-sales');
insert into skill (skillID, skillname) values (346, 'Switchboard Operator');
insert into skill (skillID, skillname) values (347, 'CFX');
insert into skill (skillID, skillname) values (348, 'Applied Behavior Analysis');
insert into skill (skillID, skillname) values (349, 'HTML Emails');
insert into skill (skillID, skillname) values (350, 'SRX');
insert into skill (skillID, skillname) values (351, 'Online Travel');
insert into skill (skillID, skillname) values (352, 'MSP Practitioner');
insert into skill (skillID, skillname) values (353, 'Rugby Union');
insert into skill (skillID, skillname) values (354, 'Cultural Awareness');
insert into skill (skillID, skillname) values (355, 'Visual Arts');
insert into skill (skillID, skillname) values (356, 'Small Business Marketing');
insert into skill (skillID, skillname) values (357, 'Analytical Ultracentrifugation');
insert into skill (skillID, skillname) values (358, 'Spring DM');
insert into skill (skillID, skillname) values (359, 'MbUnit');
insert into skill (skillID, skillname) values (360, 'QS9000');
insert into skill (skillID, skillname) values (361, 'Investments');
insert into skill (skillID, skillname) values (362, 'American Welding Society (AWS)');
insert into skill (skillID, skillname) values (363, 'Omnibus');
insert into skill (skillID, skillname) values (364, 'Karate');
insert into skill (skillID, skillname) values (365, 'Political Risk Analysis');
insert into skill (skillID, skillname) values (366, 'XMLBeans');
insert into skill (skillID, skillname) values (367, 'RMI');
insert into skill (skillID, skillname) values (368, 'Pharmacy');
insert into skill (skillID, skillname) values (369, 'Doors');
insert into skill (skillID, skillname) values (370, 'Geological Mapping');
insert into skill (skillID, skillname) values (371, 'ADP ezLaborManager');
insert into skill (skillID, skillname) values (372, 'Characterization');
insert into skill (skillID, skillname) values (373, 'KML');
insert into skill (skillID, skillname) values (374, 'ODBC');
insert into skill (skillID, skillname) values (375, 'Elder Care');
insert into skill (skillID, skillname) values (376, 'Servers');
insert into skill (skillID, skillname) values (377, 'SQL Loader');
insert into skill (skillID, skillname) values (378, 'Umbrella Insurance');
insert into skill (skillID, skillname) values (379, 'Blender');
insert into skill (skillID, skillname) values (380, 'User Interface');
insert into skill (skillID, skillname) values (381, 'IVR');
insert into skill (skillID, skillname) values (382, 'Baan ERP');
insert into skill (skillID, skillname) values (383, 'Regulatory Affairs');
insert into skill (skillID, skillname) values (384, 'Xen');
insert into skill (skillID, skillname) values (385, 'Kaizen Blitz');
insert into skill (skillID, skillname) values (386, 'MSC Patran');
insert into skill (skillID, skillname) values (387, 'Russian');
insert into skill (skillID, skillname) values (388, 'Administrative Law');
insert into skill (skillID, skillname) values (389, 'DWDM');
insert into skill (skillID, skillname) values (390, 'UWB');
insert into skill (skillID, skillname) values (391, 'RSA enVision');
insert into skill (skillID, skillname) values (392, 'CNC Manufacturing');
insert into skill (skillID, skillname) values (393, 'Yardi Voyager');
insert into skill (skillID, skillname) values (394, 'IBM iSeries');
insert into skill (skillID, skillname) values (395, 'Grief Counseling');
insert into skill (skillID, skillname) values (396, 'DFP');
insert into skill (skillID, skillname) values (397, 'VMware Infrastructure');
insert into skill (skillID, skillname) values (398, 'Temporary Placement');
insert into skill (skillID, skillname) values (399, 'Web Applications');
insert into skill (skillID, skillname) values (400, 'Typeface Design');
insert into skill (skillID, skillname) values (401, 'Enterprise Risk Management');
insert into skill (skillID, skillname) values (402, 'Kronos WFC');
insert into skill (skillID, skillname) values (403, 'Klarity');
insert into skill (skillID, skillname) values (404, 'Ultrasound Therapy');
insert into skill (skillID, skillname) values (405, 'LDAR');
insert into skill (skillID, skillname) values (406, 'Test Equipment');
insert into skill (skillID, skillname) values (407, 'Political Risk Analysis');
insert into skill (skillID, skillname) values (408, 'LPAR');
insert into skill (skillID, skillname) values (409, 'Yamaha M7CL');
insert into skill (skillID, skillname) values (410, 'LLDPE');
insert into skill (skillID, skillname) values (411, 'Appraisals');
insert into skill (skillID, skillname) values (412, 'Oz Principle');
insert into skill (skillID, skillname) values (413, 'VB.NET');
insert into skill (skillID, skillname) values (414, 'GTAW');
insert into skill (skillID, skillname) values (415, 'XaaS');
insert into skill (skillID, skillname) values (416, 'Patrol');
insert into skill (skillID, skillname) values (417, 'VSS');
insert into skill (skillID, skillname) values (418, 'Ticket Sales');
insert into skill (skillID, skillname) values (419, 'Transitional Justice');
insert into skill (skillID, skillname) values (420, 'Soft Skills');
insert into skill (skillID, skillname) values (421, 'Journal Entries');
insert into skill (skillID, skillname) values (422, 'Customer Acquisition');
insert into skill (skillID, skillname) values (423, 'HP Storage');
insert into skill (skillID, skillname) values (424, 'Literacy');
insert into skill (skillID, skillname) values (425, 'Business Analysis');
insert into skill (skillID, skillname) values (426, 'Quality Control');
insert into skill (skillID, skillname) values (427, 'USDA');
insert into skill (skillID, skillname) values (428, 'CDMA');
insert into skill (skillID, skillname) values (429, 'LN');
insert into skill (skillID, skillname) values (430, 'LDRA');
insert into skill (skillID, skillname) values (431, 'JCO');
insert into skill (skillID, skillname) values (432, 'Physician Relations');
insert into skill (skillID, skillname) values (433, 'RFP Generation');
insert into skill (skillID, skillname) values (434, 'JWICS');
insert into skill (skillID, skillname) values (435, 'Radio Broadcasting');
insert into skill (skillID, skillname) values (436, 'General Surgery');
insert into skill (skillID, skillname) values (437, 'MWS');
insert into skill (skillID, skillname) values (438, 'CDM');
insert into skill (skillID, skillname) values (439, 'Flex');
insert into skill (skillID, skillname) values (440, 'Workforce Development');
insert into skill (skillID, skillname) values (441, 'DVB-RCS');
insert into skill (skillID, skillname) values (442, 'SRM');
insert into skill (skillID, skillname) values (443, 'Urbanism');
insert into skill (skillID, skillname) values (444, 'Jerseys');
insert into skill (skillID, skillname) values (445, 'Economic Modeling');
insert into skill (skillID, skillname) values (446, 'PLC Allen Bradley');
insert into skill (skillID, skillname) values (447, 'Freelance Writing');
insert into skill (skillID, skillname) values (448, 'Marketing Strategy');
insert into skill (skillID, skillname) values (449, 'VAT');
insert into skill (skillID, skillname) values (450, 'Web Applications');
insert into skill (skillID, skillname) values (451, 'FTTH');
insert into skill (skillID, skillname) values (452, 'Fluid Mechanics');
insert into skill (skillID, skillname) values (453, 'Slickline');
insert into skill (skillID, skillname) values (454, 'Family Therapy');
insert into skill (skillID, skillname) values (455, 'Google Earth');
insert into skill (skillID, skillname) values (456, 'CDPE');
insert into skill (skillID, skillname) values (457, 'UV coating');
insert into skill (skillID, skillname) values (458, 'UIKit');
insert into skill (skillID, skillname) values (459, 'Systems Engineering');
insert into skill (skillID, skillname) values (460, 'Latin American Studies');
insert into skill (skillID, skillname) values (461, 'DVD Studio Pro');
insert into skill (skillID, skillname) values (462, 'Linux');
insert into skill (skillID, skillname) values (463, 'Coaching');
insert into skill (skillID, skillname) values (464, 'FX Animation');
insert into skill (skillID, skillname) values (465, 'Catering');
insert into skill (skillID, skillname) values (466, 'Vectorworks');
insert into skill (skillID, skillname) values (467, 'MXG');
insert into skill (skillID, skillname) values (468, 'SQL Tuning');
insert into skill (skillID, skillname) values (469, 'Rehabilitation Psychology');
insert into skill (skillID, skillname) values (470, 'CNOR');
insert into skill (skillID, skillname) values (471, 'White Collar Criminal Defense');
insert into skill (skillID, skillname) values (472, 'Aerohive');
insert into skill (skillID, skillname) values (473, 'RSVP-TE');
insert into skill (skillID, skillname) values (474, 'Wide Format Printing');
insert into skill (skillID, skillname) values (475, 'Google Docs');
insert into skill (skillID, skillname) values (476, 'JBoss EAP');
insert into skill (skillID, skillname) values (477, 'Voice Acting');
insert into skill (skillID, skillname) values (478, 'Group Dynamics');
insert into skill (skillID, skillname) values (479, 'Smartstream TLM');
insert into skill (skillID, skillname) values (480, 'IFC');
insert into skill (skillID, skillname) values (481, 'SQL Loader');
insert into skill (skillID, skillname) values (482, 'Environmental Impact Assessment');
insert into skill (skillID, skillname) values (483, 'HSS');
insert into skill (skillID, skillname) values (484, 'LDPE');
insert into skill (skillID, skillname) values (485, 'Scripting');
insert into skill (skillID, skillname) values (486, 'HP Quality Center');
insert into skill (skillID, skillname) values (487, 'Curating');
insert into skill (skillID, skillname) values (488, 'Troubleshooting');
insert into skill (skillID, skillname) values (489, 'Ignatian Spirituality');
insert into skill (skillID, skillname) values (490, 'Photography');
insert into skill (skillID, skillname) values (491, 'Newsletters');
insert into skill (skillID, skillname) values (492, 'IAD');
insert into skill (skillID, skillname) values (493, 'Counseling Psychology');
insert into skill (skillID, skillname) values (494, 'VJ');
insert into skill (skillID, skillname) values (495, 'Non-profit Administration');
insert into skill (skillID, skillname) values (496, 'Oxygen');
insert into skill (skillID, skillname) values (497, 'Ab Initio');
insert into skill (skillID, skillname) values (498, 'PPAP');
insert into skill (skillID, skillname) values (499, 'Pro Tools');
insert into skill (skillID, skillname) values (500, 'GIS');
insert into skill (skillID, skillname) values (501, 'Skin Care');
insert into skill (skillID, skillname) values (502, 'GIS Modeling');
insert into skill (skillID, skillname) values (503, 'XFS');
insert into skill (skillID, skillname) values (504, 'Location Intelligence');
insert into skill (skillID, skillname) values (505, 'Feature Writing');
insert into skill (skillID, skillname) values (506, 'Easytrieve');
insert into skill (skillID, skillname) values (507, 'CNC Manufacturing');
insert into skill (skillID, skillname) values (508, 'Branch Banking');
insert into skill (skillID, skillname) values (509, 'Zuora');
insert into skill (skillID, skillname) values (510, 'Compensation &amp; Benefits');
insert into skill (skillID, skillname) values (511, 'Big 4');
insert into skill (skillID, skillname) values (512, 'ISO 13485');
insert into skill (skillID, skillname) values (513, 'RSLogix');
insert into skill (skillID, skillname) values (514, 'HD Camera Operation');
insert into skill (skillID, skillname) values (515, 'Software Design');
insert into skill (skillID, skillname) values (516, 'McKesson STAR');
insert into skill (skillID, skillname) values (517, 'Solar PV');
insert into skill (skillID, skillname) values (518, 'Unit Testing');
insert into skill (skillID, skillname) values (519, 'Yarn');
insert into skill (skillID, skillname) values (520, 'CgFX');
insert into skill (skillID, skillname) values (521, 'Business Intelligence');
insert into skill (skillID, skillname) values (522, 'RRC');
insert into skill (skillID, skillname) values (523, 'JDK');
insert into skill (skillID, skillname) values (524, 'VMware vCenter');
insert into skill (skillID, skillname) values (525, 'Ghostwriting');
insert into skill (skillID, skillname) values (526, 'JiBX');
insert into skill (skillID, skillname) values (527, 'DLL');
insert into skill (skillID, skillname) values (528, 'JMeter');
insert into skill (skillID, skillname) values (529, 'Supervisory Skills');
insert into skill (skillID, skillname) values (530, 'Systems Analysis');
insert into skill (skillID, skillname) values (531, 'IFTA');
insert into skill (skillID, skillname) values (532, 'Vascular');
insert into skill (skillID, skillname) values (533, 'Business Transformation');
insert into skill (skillID, skillname) values (534, 'RMAN');
insert into skill (skillID, skillname) values (535, 'FTIR');
insert into skill (skillID, skillname) values (536, 'Jazz Dance');
insert into skill (skillID, skillname) values (537, 'Cell');
insert into skill (skillID, skillname) values (538, 'Hazard Analysis');
insert into skill (skillID, skillname) values (539, 'RTI');
insert into skill (skillID, skillname) values (540, 'EH&amp;S Compliance');
insert into skill (skillID, skillname) values (541, 'WSRR');
insert into skill (skillID, skillname) values (542, 'SRTP');
insert into skill (skillID, skillname) values (543, 'Red Hat Linux');
insert into skill (skillID, skillname) values (544, 'Jeet Kune Do');
insert into skill (skillID, skillname) values (545, 'SBR');
insert into skill (skillID, skillname) values (546, 'RoboHelp');
insert into skill (skillID, skillname) values (547, 'Teeth Whitening');
insert into skill (skillID, skillname) values (548, 'Vehicle Dynamics');
insert into skill (skillID, skillname) values (549, 'Screening Resumes');
insert into skill (skillID, skillname) values (550, 'HMO');
insert into skill (skillID, skillname) values (551, 'GXT');
insert into skill (skillID, skillname) values (552, 'Small Business Development');
insert into skill (skillID, skillname) values (553, 'Octave');
insert into skill (skillID, skillname) values (554, 'OLT');
insert into skill (skillID, skillname) values (555, 'TTD');
insert into skill (skillID, skillname) values (556, 'Kaizen Leadership');
insert into skill (skillID, skillname) values (557, 'Virtual PC');
insert into skill (skillID, skillname) values (558, 'Kofax');
insert into skill (skillID, skillname) values (559, 'Db4o');
insert into skill (skillID, skillname) values (560, 'DVB');
insert into skill (skillID, skillname) values (561, 'Wildlife');
insert into skill (skillID, skillname) values (562, 'MV');
insert into skill (skillID, skillname) values (563, 'VCAT');
insert into skill (skillID, skillname) values (564, 'Oligonucleotide Synthesis');
insert into skill (skillID, skillname) values (565, 'ISO/TS 16949');
insert into skill (skillID, skillname) values (566, 'MLP');
insert into skill (skillID, skillname) values (567, 'Agronomy');
insert into skill (skillID, skillname) values (568, 'Cell');
insert into skill (skillID, skillname) values (569, 'MVS');
insert into skill (skillID, skillname) values (570, 'Key Account Development');
insert into skill (skillID, skillname) values (571, 'XPDL');
insert into skill (skillID, skillname) values (572, 'GWAS');
insert into skill (skillID, skillname) values (573, 'Klarity');
insert into skill (skillID, skillname) values (574, 'Rock Climbing');
insert into skill (skillID, skillname) values (575, 'FDT');
insert into skill (skillID, skillname) values (576, 'Community Organizing');
insert into skill (skillID, skillname) values (577, 'Aqualogic');
insert into skill (skillID, skillname) values (578, 'Oracle E-Business Suite');
insert into skill (skillID, skillname) values (579, 'Interviews');
insert into skill (skillID, skillname) values (580, 'Nuke');
insert into skill (skillID, skillname) values (581, 'Supporting Others');
insert into skill (skillID, skillname) values (582, 'Philanthropy');
insert into skill (skillID, skillname) values (583, 'Multi-channel Marketing');
insert into skill (skillID, skillname) values (584, 'Windows Azure');
insert into skill (skillID, skillname) values (585, 'AAT');
insert into skill (skillID, skillname) values (586, 'Human Capital Management');
insert into skill (skillID, skillname) values (587, 'Amadeus GDS');
insert into skill (skillID, skillname) values (588, 'Patient Advocacy');
insert into skill (skillID, skillname) values (589, 'RLM');
insert into skill (skillID, skillname) values (590, 'Employee Training');
insert into skill (skillID, skillname) values (591, 'LTACH');
insert into skill (skillID, skillname) values (592, 'Wwise');
insert into skill (skillID, skillname) values (593, 'Electronics');
insert into skill (skillID, skillname) values (594, 'NLog');
insert into skill (skillID, skillname) values (595, 'NBFC');
insert into skill (skillID, skillname) values (596, 'Songwriting');
insert into skill (skillID, skillname) values (597, 'Siding');
insert into skill (skillID, skillname) values (598, 'Weddings');
insert into skill (skillID, skillname) values (599, 'MVA');
insert into skill (skillID, skillname) values (600, 'Government Relations');
insert into skill (skillID, skillname) values (601, 'EBIT');
insert into skill (skillID, skillname) values (602, 'Oil Painting');
insert into skill (skillID, skillname) values (603, 'Defect Life Cycle');
insert into skill (skillID, skillname) values (604, 'MBAL');
insert into skill (skillID, skillname) values (605, 'Appointment Scheduling');
insert into skill (skillID, skillname) values (606, 'UltraTax CS');
insert into skill (skillID, skillname) values (607, 'Win CVS');
insert into skill (skillID, skillname) values (608, 'Mediation');
insert into skill (skillID, skillname) values (609, 'SAP BI');
insert into skill (skillID, skillname) values (610, 'JFreeChart');
insert into skill (skillID, skillname) values (611, 'Earned Value Management');
insert into skill (skillID, skillname) values (612, 'KVM');
insert into skill (skillID, skillname) values (613, 'Tax Preparation');
insert into skill (skillID, skillname) values (614, 'IRI');
insert into skill (skillID, skillname) values (615, 'Twitter Marketing');
insert into skill (skillID, skillname) values (616, 'Simple IRA');
insert into skill (skillID, skillname) values (617, 'MicroStation');
insert into skill (skillID, skillname) values (618, 'FCNSA');
insert into skill (skillID, skillname) values (619, 'eWFM');
insert into skill (skillID, skillname) values (620, 'Leave of Absence');
insert into skill (skillID, skillname) values (621, 'Editorial');
insert into skill (skillID, skillname) values (622, 'MBCS');
insert into skill (skillID, skillname) values (623, 'IFW');
insert into skill (skillID, skillname) values (624, 'RHIT');
insert into skill (skillID, skillname) values (625, 'Ubercart');
insert into skill (skillID, skillname) values (626, 'Supply Chain Optimization');
insert into skill (skillID, skillname) values (627, 'DCF Valuation');
insert into skill (skillID, skillname) values (628, 'RSView');
insert into skill (skillID, skillname) values (629, 'Security Audits');
insert into skill (skillID, skillname) values (630, 'XFP');
insert into skill (skillID, skillname) values (631, 'Lloyds');
insert into skill (skillID, skillname) values (632, 'Powers of Attorney');
insert into skill (skillID, skillname) values (633, 'Jewish Studies');
insert into skill (skillID, skillname) values (634, 'Epigenetics');
insert into skill (skillID, skillname) values (635, 'Keyshot');
insert into skill (skillID, skillname) values (636, 'Cerner');
insert into skill (skillID, skillname) values (637, 'Gas Turbines');
insert into skill (skillID, skillname) values (638, 'PKCS');
insert into skill (skillID, skillname) values (639, 'User Scenarios');
insert into skill (skillID, skillname) values (640, 'Variable Frequency Drives');
insert into skill (skillID, skillname) values (641, 'RRIF');
insert into skill (skillID, skillname) values (642, 'CBCP');
insert into skill (skillID, skillname) values (643, 'Vectorworks');
insert into skill (skillID, skillname) values (644, 'Procurement');
insert into skill (skillID, skillname) values (645, 'Process Improvement');
insert into skill (skillID, skillname) values (646, 'Business Process Improvement');
insert into skill (skillID, skillname) values (647, 'Oracle');
insert into skill (skillID, skillname) values (648, 'SBMS');
insert into skill (skillID, skillname) values (649, 'Wildlife');
insert into skill (skillID, skillname) values (650, 'JTest');
insert into skill (skillID, skillname) values (651, 'UCINET');
insert into skill (skillID, skillname) values (652, 'Web TV');
insert into skill (skillID, skillname) values (653, 'SAP Implementation');
insert into skill (skillID, skillname) values (654, 'OWL');
insert into skill (skillID, skillname) values (655, 'Data Entry');
insert into skill (skillID, skillname) values (656, 'Usability Engineering');
insert into skill (skillID, skillname) values (657, 'CDMA');
insert into skill (skillID, skillname) values (658, 'SDSF');
insert into skill (skillID, skillname) values (659, 'Management by Objectives');
insert into skill (skillID, skillname) values (660, 'Photojournalism');
insert into skill (skillID, skillname) values (661, 'CNS disorders');
insert into skill (skillID, skillname) values (662, 'Job Costing');
insert into skill (skillID, skillname) values (663, 'Global Mobility');
insert into skill (skillID, skillname) values (664, 'Underground Mining');
insert into skill (skillID, skillname) values (665, 'Waste');
insert into skill (skillID, skillname) values (666, 'Business Process Improvement');
insert into skill (skillID, skillname) values (667, 'Jigs');
insert into skill (skillID, skillname) values (668, 'IVUS');
insert into skill (skillID, skillname) values (669, 'EASA');
insert into skill (skillID, skillname) values (670, 'Logistics');
insert into skill (skillID, skillname) values (671, 'FMS');
insert into skill (skillID, skillname) values (672, 'Nonprofits');
insert into skill (skillID, skillname) values (673, 'Krakatoa');
insert into skill (skillID, skillname) values (674, 'Sniffer');
insert into skill (skillID, skillname) values (675, 'Object Oriented Perl');
insert into skill (skillID, skillname) values (676, 'CATIA');
insert into skill (skillID, skillname) values (677, 'DLL');
insert into skill (skillID, skillname) values (678, 'Ion Exchange');
insert into skill (skillID, skillname) values (679, 'DFU');
insert into skill (skillID, skillname) values (680, 'Handmade Jewelry');
insert into skill (skillID, skillname) values (681, 'Youth Marketing');
insert into skill (skillID, skillname) values (682, 'Military Logistics');
insert into skill (skillID, skillname) values (683, 'RTK');
insert into skill (skillID, skillname) values (684, 'DDM');
insert into skill (skillID, skillname) values (685, 'Turbomachinery');
insert into skill (skillID, skillname) values (686, 'JUnit');
insert into skill (skillID, skillname) values (687, 'White Box Testing');
insert into skill (skillID, skillname) values (688, 'LDRPS');
insert into skill (skillID, skillname) values (689, 'SNP genotyping');
insert into skill (skillID, skillname) values (690, 'NDF');
insert into skill (skillID, skillname) values (691, 'Oracle XE');
insert into skill (skillID, skillname) values (692, 'Wastewater Treatment');
insert into skill (skillID, skillname) values (693, 'Lumion');
insert into skill (skillID, skillname) values (694, 'Self-esteem');
insert into skill (skillID, skillname) values (695, 'Production Efficiency');
insert into skill (skillID, skillname) values (696, 'Oracle XE');
insert into skill (skillID, skillname) values (697, 'MDL');
insert into skill (skillID, skillname) values (698, 'MDOP');
insert into skill (skillID, skillname) values (699, 'EJB');
insert into skill (skillID, skillname) values (700, 'Zend Studio');
insert into skill (skillID, skillname) values (701, 'CMMI Level 5');
insert into skill (skillID, skillname) values (702, 'CBRN');
insert into skill (skillID, skillname) values (703, 'Unit Testing');
insert into skill (skillID, skillname) values (704, 'Cycle Counting');
insert into skill (skillID, skillname) values (705, 'Office Equipment');
insert into skill (skillID, skillname) values (706, 'ACLS');
insert into skill (skillID, skillname) values (707, 'FX Trading');
insert into skill (skillID, skillname) values (708, 'GMI');
insert into skill (skillID, skillname) values (709, 'McKesson PACS');
insert into skill (skillID, skillname) values (710, 'Cyber Defense');
insert into skill (skillID, skillname) values (711, 'Spring DM');
insert into skill (skillID, skillname) values (712, 'Online Help');
insert into skill (skillID, skillname) values (713, 'Live Events');
insert into skill (skillID, skillname) values (714, 'DC Operations');
insert into skill (skillID, skillname) values (715, 'NCS');
insert into skill (skillID, skillname) values (716, 'Linux System Administration');
insert into skill (skillID, skillname) values (717, 'FDTD');
insert into skill (skillID, skillname) values (718, 'UltraEdit');
insert into skill (skillID, skillname) values (719, 'RPM');
insert into skill (skillID, skillname) values (720, 'Piano');
insert into skill (skillID, skillname) values (721, 'Career Development');
insert into skill (skillID, skillname) values (722, 'GTS');
insert into skill (skillID, skillname) values (723, 'Personal Development');
insert into skill (skillID, skillname) values (724, 'Avid DS Nitris');
insert into skill (skillID, skillname) values (725, 'Windows Vista');
insert into skill (skillID, skillname) values (726, 'NNTP');
insert into skill (skillID, skillname) values (727, 'DNA methylation');
insert into skill (skillID, skillname) values (728, 'Planning');
insert into skill (skillID, skillname) values (729, 'NUnit');
insert into skill (skillID, skillname) values (730, 'Pdf');
insert into skill (skillID, skillname) values (731, 'Single Family Homes');
insert into skill (skillID, skillname) values (732, 'BMC Remedy Administration');
insert into skill (skillID, skillname) values (733, 'Photography');
insert into skill (skillID, skillname) values (734, 'FPS');
insert into skill (skillID, skillname) values (735, 'Cisco MDS SAN switches');
insert into skill (skillID, skillname) values (736, 'FCAW');
insert into skill (skillID, skillname) values (737, 'IABP');
insert into skill (skillID, skillname) values (738, 'JVM');
insert into skill (skillID, skillname) values (739, 'Financial Statements');
insert into skill (skillID, skillname) values (740, 'DFMEA');
insert into skill (skillID, skillname) values (741, 'MSDS');
insert into skill (skillID, skillname) values (742, 'HCSS');
insert into skill (skillID, skillname) values (743, 'CMMS');
insert into skill (skillID, skillname) values (744, 'Yardi');
insert into skill (skillID, skillname) values (745, 'Social Psychology');
insert into skill (skillID, skillname) values (746, 'Oxygen XML Editor');
insert into skill (skillID, skillname) values (747, 'EOU');
insert into skill (skillID, skillname) values (748, 'Offshore Oil &amp; Gas');
insert into skill (skillID, skillname) values (749, 'What-if Analysis');
insert into skill (skillID, skillname) values (750, 'Kyocera');
insert into skill (skillID, skillname) values (751, 'PyMEL');
insert into skill (skillID, skillname) values (752, 'RHIA');
insert into skill (skillID, skillname) values (753, 'Land Use Planning');
insert into skill (skillID, skillname) values (754, 'Sybase SQL Anywhere');
insert into skill (skillID, skillname) values (755, 'PVTsim');
insert into skill (skillID, skillname) values (756, 'Xilinx');
insert into skill (skillID, skillname) values (757, 'Avid Xpress');
insert into skill (skillID, skillname) values (758, 'Basel II');
insert into skill (skillID, skillname) values (759, 'Medical Imaging');
insert into skill (skillID, skillname) values (760, 'Music Videos');
insert into skill (skillID, skillname) values (761, 'Urban Forestry');
insert into skill (skillID, skillname) values (762, 'Nagios');
insert into skill (skillID, skillname) values (763, 'Alcoholic Beverages');
insert into skill (skillID, skillname) values (764, 'EoMPLS');
insert into skill (skillID, skillname) values (765, 'VPN');
insert into skill (skillID, skillname) values (766, 'Wellbeing');
insert into skill (skillID, skillname) values (767, 'Television');
insert into skill (skillID, skillname) values (768, 'CFML');
insert into skill (skillID, skillname) values (769, 'Type Approval');
insert into skill (skillID, skillname) values (770, 'Zsh');
insert into skill (skillID, skillname) values (771, 'Artistic Eye');
insert into skill (skillID, skillname) values (772, 'JCE');
insert into skill (skillID, skillname) values (773, 'Urban Design');
insert into skill (skillID, skillname) values (774, 'Olive Oil');
insert into skill (skillID, skillname) values (775, 'CMBS');
insert into skill (skillID, skillname) values (776, 'Formation Evaluation');
insert into skill (skillID, skillname) values (777, 'DC Drives');
insert into skill (skillID, skillname) values (778, 'Title Searches');
insert into skill (skillID, skillname) values (779, 'Executive Protection');
insert into skill (skillID, skillname) values (780, 'SMT');
insert into skill (skillID, skillname) values (781, 'Report Writing');
insert into skill (skillID, skillname) values (782, 'SDLX');
insert into skill (skillID, skillname) values (783, 'Environmental Impact Assessment');
insert into skill (skillID, skillname) values (784, 'Accounting');
insert into skill (skillID, skillname) values (785, 'Executive Search');
insert into skill (skillID, skillname) values (786, 'GHS');
insert into skill (skillID, skillname) values (787, 'MQSI');
insert into skill (skillID, skillname) values (788, 'Church Growth');
insert into skill (skillID, skillname) values (789, 'ISM');
insert into skill (skillID, skillname) values (790, 'GxP');
insert into skill (skillID, skillname) values (791, 'Lutron');
insert into skill (skillID, skillname) values (792, 'DTE');
insert into skill (skillID, skillname) values (793, 'Python');
insert into skill (skillID, skillname) values (794, 'Editing');
insert into skill (skillID, skillname) values (795, 'Secretarial Skills');
insert into skill (skillID, skillname) values (796, 'ILS');
insert into skill (skillID, skillname) values (797, 'UIM');
insert into skill (skillID, skillname) values (798, 'Awareness Raising');
insert into skill (skillID, skillname) values (799, 'VMD');
insert into skill (skillID, skillname) values (800, 'OCR');
insert into skill (skillID, skillname) values (801, 'Overcome Objections');
insert into skill (skillID, skillname) values (802, 'FPGA prototyping');
insert into skill (skillID, skillname) values (803, 'IQ Navigator');
insert into skill (skillID, skillname) values (804, 'Hotels');
insert into skill (skillID, skillname) values (805, 'BPEL');
insert into skill (skillID, skillname) values (806, 'GWT');
insert into skill (skillID, skillname) values (807, 'HSE Management Systems');
insert into skill (skillID, skillname) values (808, 'Blood Pressure');
insert into skill (skillID, skillname) values (809, 'BSC');
insert into skill (skillID, skillname) values (810, 'BJT');
insert into skill (skillID, skillname) values (811, 'High Sense Of Urgency');
insert into skill (skillID, skillname) values (812, 'Oil Paint');
insert into skill (skillID, skillname) values (813, 'JCreator');
insert into skill (skillID, skillname) values (814, 'AV Integration');
insert into skill (skillID, skillname) values (815, 'Overcoming Challenges');
insert into skill (skillID, skillname) values (816, 'GT Strudl');
insert into skill (skillID, skillname) values (817, 'SMO');
insert into skill (skillID, skillname) values (818, 'PDMLink');
insert into skill (skillID, skillname) values (819, 'MyChart');
insert into skill (skillID, skillname) values (820, 'SMTP');
insert into skill (skillID, skillname) values (821, 'Financial Reporting');
insert into skill (skillID, skillname) values (822, 'NPV');
insert into skill (skillID, skillname) values (823, 'Visual Arts');
insert into skill (skillID, skillname) values (824, 'BTS Installation');
insert into skill (skillID, skillname) values (825, 'Sales Operations');
insert into skill (skillID, skillname) values (826, 'Pulse Oximetry');
insert into skill (skillID, skillname) values (827, 'Timber');
insert into skill (skillID, skillname) values (828, 'Jigs');
insert into skill (skillID, skillname) values (829, 'PSpice');
insert into skill (skillID, skillname) values (830, 'Overhead Cranes');
insert into skill (skillID, skillname) values (831, 'Fit-out');
insert into skill (skillID, skillname) values (832, 'Capital Markets');
insert into skill (skillID, skillname) values (833, 'WFA');
insert into skill (skillID, skillname) values (834, 'Project Oversight');
insert into skill (skillID, skillname) values (835, 'Egyptology');
insert into skill (skillID, skillname) values (836, 'Multimedia');
insert into skill (skillID, skillname) values (837, 'IRI Xlerate');
insert into skill (skillID, skillname) values (838, 'CDMA');
insert into skill (skillID, skillname) values (839, 'Rsync');
insert into skill (skillID, skillname) values (840, 'Self-esteem');
insert into skill (skillID, skillname) values (841, 'PDE');
insert into skill (skillID, skillname) values (842, 'DCF');
insert into skill (skillID, skillname) values (843, 'MCH');
insert into skill (skillID, skillname) values (844, 'Sweaters');
insert into skill (skillID, skillname) values (845, 'Ticketing');
insert into skill (skillID, skillname) values (846, 'nDo');
insert into skill (skillID, skillname) values (847, 'Contract Negotiation');
insert into skill (skillID, skillname) values (848, 'Transportation Management');
insert into skill (skillID, skillname) values (849, 'Human Resource Planning');
insert into skill (skillID, skillname) values (850, 'Blogger');
insert into skill (skillID, skillname) values (851, 'Small Business Marketing');
insert into skill (skillID, skillname) values (852, 'Oil &amp; Gas Services');
insert into skill (skillID, skillname) values (853, 'Krakatoa');
insert into skill (skillID, skillname) values (854, 'FEED');
insert into skill (skillID, skillname) values (855, 'VTR');
insert into skill (skillID, skillname) values (856, 'Branch Banking');
insert into skill (skillID, skillname) values (857, 'Business Analysis');
insert into skill (skillID, skillname) values (858, 'RNA');
insert into skill (skillID, skillname) values (859, 'TPU');
insert into skill (skillID, skillname) values (860, 'Welding');
insert into skill (skillID, skillname) values (861, 'TGI');
insert into skill (skillID, skillname) values (862, 'Automotive Engineering');
insert into skill (skillID, skillname) values (863, 'TMA');
insert into skill (skillID, skillname) values (864, 'Gaming Industry');
insert into skill (skillID, skillname) values (865, 'Epigenetics');
insert into skill (skillID, skillname) values (866, 'BPH');
insert into skill (skillID, skillname) values (867, 'ILS');
insert into skill (skillID, skillname) values (868, 'zSeries');
insert into skill (skillID, skillname) values (869, 'NAS');
insert into skill (skillID, skillname) values (870, 'eCTD');
insert into skill (skillID, skillname) values (871, 'Materials Science');
insert into skill (skillID, skillname) values (872, 'Yarn');
insert into skill (skillID, skillname) values (873, 'Trade Marketing');
insert into skill (skillID, skillname) values (874, 'HSRP');
insert into skill (skillID, skillname) values (875, 'CD Mastering');
insert into skill (skillID, skillname) values (876, 'Zyxel');
insert into skill (skillID, skillname) values (877, 'Oz Principle');
insert into skill (skillID, skillname) values (878, 'CTFL');
insert into skill (skillID, skillname) values (879, 'Juvenile Law');
insert into skill (skillID, skillname) values (880, 'RT-PCR');
insert into skill (skillID, skillname) values (881, 'Software Quality Assurance');
insert into skill (skillID, skillname) values (882, 'High Availability');
insert into skill (skillID, skillname) values (883, 'QCAT');
insert into skill (skillID, skillname) values (884, 'IP Cameras');
insert into skill (skillID, skillname) values (885, 'JNCIP');
insert into skill (skillID, skillname) values (886, 'SBEM');
insert into skill (skillID, skillname) values (887, 'FDCPA');
insert into skill (skillID, skillname) values (888, 'MBR');
insert into skill (skillID, skillname) values (889, 'iVantage');
insert into skill (skillID, skillname) values (890, 'AOP');
insert into skill (skillID, skillname) values (891, 'European Markets');
insert into skill (skillID, skillname) values (892, 'UV Mapping');
insert into skill (skillID, skillname) values (893, 'Web Development');
insert into skill (skillID, skillname) values (894, 'Participant Observation');
insert into skill (skillID, skillname) values (895, 'NDC');
insert into skill (skillID, skillname) values (896, 'Waterfront');
insert into skill (skillID, skillname) values (897, 'Basic HTML');
insert into skill (skillID, skillname) values (898, 'Observational Studies');
insert into skill (skillID, skillname) values (899, 'NVR');
insert into skill (skillID, skillname) values (900, 'NCARB');
insert into skill (skillID, skillname) values (901, 'Smarty');
insert into skill (skillID, skillname) values (902, 'Epic Systems');
insert into skill (skillID, skillname) values (903, 'JBoss ESB');
insert into skill (skillID, skillname) values (904, 'Koha');
insert into skill (skillID, skillname) values (905, 'HLA');
insert into skill (skillID, skillname) values (906, 'DV');
insert into skill (skillID, skillname) values (907, 'Waterfall');
insert into skill (skillID, skillname) values (908, 'GNU Debugger');
insert into skill (skillID, skillname) values (909, 'Urgent Care');
insert into skill (skillID, skillname) values (910, 'Supply Management');
insert into skill (skillID, skillname) values (911, 'USDA Rural Housing');
insert into skill (skillID, skillname) values (912, 'Time Management');
insert into skill (skillID, skillname) values (913, 'KDevelop');
insert into skill (skillID, skillname) values (914, 'HTML Scripting');
insert into skill (skillID, skillname) values (915, 'General Ledger');
insert into skill (skillID, skillname) values (916, 'MP2');
insert into skill (skillID, skillname) values (917, 'Wholesale');
insert into skill (skillID, skillname) values (918, 'VC#');
insert into skill (skillID, skillname) values (919, 'Time-efficient');
insert into skill (skillID, skillname) values (920, 'MFR');
insert into skill (skillID, skillname) values (921, 'IT Management');
insert into skill (skillID, skillname) values (922, 'RGB');
insert into skill (skillID, skillname) values (923, 'Claim');
insert into skill (skillID, skillname) values (924, 'CPAP');
insert into skill (skillID, skillname) values (925, 'Uniform Combined State Law');
insert into skill (skillID, skillname) values (926, 'SIP Trunking');
insert into skill (skillID, skillname) values (927, 'Academic Writing');
insert into skill (skillID, skillname) values (928, 'Production Efficiency');
insert into skill (skillID, skillname) values (929, 'Land Use Planning');
insert into skill (skillID, skillname) values (930, 'OCR');
insert into skill (skillID, skillname) values (931, 'OGRE');
insert into skill (skillID, skillname) values (932, 'PFlow');
insert into skill (skillID, skillname) values (933, 'HTML Help Workshop');
insert into skill (skillID, skillname) values (934, 'Turbo C++');
insert into skill (skillID, skillname) values (935, 'LDP');
insert into skill (skillID, skillname) values (936, 'Algorithms');
insert into skill (skillID, skillname) values (937, 'Life Insurance');
insert into skill (skillID, skillname) values (938, 'PDMS');
insert into skill (skillID, skillname) values (939, 'Yacht Charters');
insert into skill (skillID, skillname) values (940, 'IWR');
insert into skill (skillID, skillname) values (941, 'Aeronautics');
insert into skill (skillID, skillname) values (942, 'RC Detailing');
insert into skill (skillID, skillname) values (943, 'Sketching');
insert into skill (skillID, skillname) values (944, 'Non-profit Board Development');
insert into skill (skillID, skillname) values (945, 'Breaking News');
insert into skill (skillID, skillname) values (946, 'Yacht Clubs');
insert into skill (skillID, skillname) values (947, 'ADP HRB');
insert into skill (skillID, skillname) values (948, 'Jazz Dance');
insert into skill (skillID, skillname) values (949, 'MSS');
insert into skill (skillID, skillname) values (950, 'Public Relations');
insert into skill (skillID, skillname) values (951, 'HRO');
insert into skill (skillID, skillname) values (952, 'Jewish History');
insert into skill (skillID, skillname) values (953, 'Business Strategy');
insert into skill (skillID, skillname) values (954, 'UDP');
insert into skill (skillID, skillname) values (955, 'McData');
insert into skill (skillID, skillname) values (956, 'TMX');
insert into skill (skillID, skillname) values (957, 'Dog Training');
insert into skill (skillID, skillname) values (958, 'HD Video');
insert into skill (skillID, skillname) values (959, 'cPanel');
insert into skill (skillID, skillname) values (960, 'XPath');
insert into skill (skillID, skillname) values (961, 'SFIA');
insert into skill (skillID, skillname) values (962, 'WFS');
insert into skill (skillID, skillname) values (963, 'Typo3');
insert into skill (skillID, skillname) values (964, 'MPLAB');
insert into skill (skillID, skillname) values (965, 'ATM Networks');
insert into skill (skillID, skillname) values (966, 'XP Professional');
insert into skill (skillID, skillname) values (967, 'CTM');
insert into skill (skillID, skillname) values (968, 'BMR');
insert into skill (skillID, skillname) values (969, 'HMS');
insert into skill (skillID, skillname) values (970, 'Development Economics');
insert into skill (skillID, skillname) values (971, 'DFMA');
insert into skill (skillID, skillname) values (972, 'Recruitment Advertising');
insert into skill (skillID, skillname) values (973, 'Zoology');
insert into skill (skillID, skillname) values (974, 'Aerial Cinematography');
insert into skill (skillID, skillname) values (975, 'Life Insurance');
insert into skill (skillID, skillname) values (976, 'Real Estate License');
insert into skill (skillID, skillname) values (977, 'JIS');
insert into skill (skillID, skillname) values (978, 'SQLite');
insert into skill (skillID, skillname) values (979, 'PDM Works');
insert into skill (skillID, skillname) values (980, 'IES VE');
insert into skill (skillID, skillname) values (981, 'LTACH');
insert into skill (skillID, skillname) values (982, 'Sleep Apnea');
insert into skill (skillID, skillname) values (983, 'Ocular Disease');
insert into skill (skillID, skillname) values (984, 'Zenworks');
insert into skill (skillID, skillname) values (985, 'Play Therapy');
insert into skill (skillID, skillname) values (986, 'CCU');
insert into skill (skillID, skillname) values (987, 'TyMetrix');
insert into skill (skillID, skillname) values (988, 'iPhone Application Development');
insert into skill (skillID, skillname) values (989, 'Piano Education');
insert into skill (skillID, skillname) values (990, 'PTS');
insert into skill (skillID, skillname) values (991, 'JDE CNC');
insert into skill (skillID, skillname) values (992, 'XBR');
insert into skill (skillID, skillname) values (993, 'Yacht Racing');
insert into skill (skillID, skillname) values (994, 'Not for Profit');
insert into skill (skillID, skillname) values (995, 'HVAC Controls');
insert into skill (skillID, skillname) values (996, 'Knowledge Sharing');
insert into skill (skillID, skillname) values (997, 'Fleet Management');
insert into skill (skillID, skillname) values (998, 'Vendor Management');
insert into skill (skillID, skillname) values (999, 'Business Process Improvement');
insert into skill (skillID, skillname) values (1000, 'Audio Editing');
